routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BenefitController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\Counsellor;
use App\Http\Controllers\CounsellorProfileController;
use App\Http\Controllers\CounsellorSessionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DownloadResultController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InstructionController;
use App\Http\Controllers\PaymentInfoController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SessionPaymentController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\User;
use App\Http\Controllers\UserCounsellorSessionController;
use App\Http\Controllers\UserPersonalInformationController;
use App\Http\Controllers\UserProfessionalController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserResultController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use App\Http\Controllers\User\VerifyPhoneController;
use App\Http\Controllers\UserTimezoneController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('coach/register', [AuthController::class, 'counsellorRegistration'])->name("coach.apply");
Route::view('coach/apply', 'counsellor.apply')->name('counsellor.apply');
Route::get('faqs', [FrontController::class, "faqs"])->name('faqs');
// Route::get('help', [FrontController::class, 'help'])->name('help');

Route::get('about', [FrontController::class, 'about'])->name('about');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::resource('contact-us', ContactUsController::class)->only(["store"]);

Route::get('counsellor-register', [AuthController::class, 'counsellorRegister']);
Route::post('counsellor-registration', [AuthController::class, 'counsellorRegister'])->name('counsellorRegister');
Route::get('school', [FrontController::class, 'school'])->name("school");
Route::get('register/{profession}', [AuthController::class, 'register']);
// added routes for new design
Route::get('get-started', [AuthController::class, 'new_signup'])->name('who-are-you');

// Route::get('get-started', [FrontController::class, 'getStarted'])->name('who-are-you');
Route::get('university', [FrontController::class, 'university'])->name("university");
Route::get('Professional', [FrontController::class, 'professional'])->name("professional");
Route::get('Parents', [FrontController::class, 'parent'])->name("parents");
Route::get('benefit/{word?}', [BenefitController::class, 'getData'])->name('benefit')->middleware(["auth", "verified"]);

Route::group(
    ['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Super Admin']],
    function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('users', Admin\UserController::class);
        Route::resource('users.professional', Admin\UserProfessionalController::class);
        Route::resource('counsellors', Admin\CounsellorController::class);
        Route::resource('tests', TestController::class);
        Route::resource('questions', QuestionController::class);
        Route::resource('payments', Admin\SessionPaymentController::class)->except(["edit", "create"]);
        Route::resource('benefits', BenefitController::class);
        Route::resource('instructions', InstructionController::class);
        Route::resource('videos', Admin\VideoController::class);
        Route::resource('faqs', FaqController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::get('changeCouponStatus', [Admin\CouponController::class, 'changeCouponStatus'])->name('coupons.changeCouponStatus');
        Route::get('changeUserStatus', [Admin\UserController::class, 'changeUserStatus'])->name('users.changeUserStatus');
        Route::get('users/{id}/change-password', [Admin\UserController::class, 'changeUserPassword'])->name('users.changeUserPassword');
        Route::post('users/{id}/update-password', [Admin\UserController::class, 'updateUserPassword'])->name('users.updateUserPassword');
        Route::get('currencies', [Admin\CurrencyController::class, 'index'])->name('currencies.index');
        Route::post('currencies/store', [Admin\CurrencyController::class, 'store'])->name('currencies.store');
        Route::get('currencies/{id}/edit', [Admin\CurrencyController::class, 'edit'])->name('currencies.edit');
        Route::put('currencies/update', [Admin\CurrencyController::class, 'update'])->name('currencies.update');
        Route::delete('currencies/{id}/delete', [Admin\CurrencyController::class, 'destroy'])->name('currencies.destroy');
        Route::get('deleted/users', [Admin\TrashedUsersController::class, 'deletedUsers'])->name('trashedUsers');
        Route::delete('deleted/users/{id}', [Admin\TrashedUsersController::class, 'deletePermanently'])->name('trashedUsers.delete');
        Route::get('deleted/coaches', [Admin\TrashedUsersController::class, 'deletedCoaches'])->name('counsellors.trashed');
        Route::get('restore/users/{id}', [Admin\TrashedUsersController::class, 'restore'])->name('users.restore');
    }
);

Route::middleware(['verified', 'auth', 'change_password'])->group(function () {
    Route::get('dashboard', [DashboardController::class, "dashboard"])->name('dashboard');
    Route::get('help', [FrontController::class, 'help'])->name('help');
    Route::POST('help', [FrontController::class, 'helpStore'])->name('help.store');
    Route::POST('user/{id}/timezone/update', [UserTimezoneController::class, 'updateUserTimezone'])->name('user.timezone.update');
});

Route::get('refresh_captcha', [FrontController::class, 'refreshCaptcha']);
Route::post('subscribe', [SubscribeController::class, 'store'])->name('subscribe');
Route::prefix("user")->as("user.")->middleware(['auth', 'verified', 'role:User'])->group(function () {
    Route::POST('connect-zoom', [UserController::class, 'connectZoomAccount'])->name("zoom.account.connect");
    Route::get('session/booking', [CounsellorProfileController::class, 'index'])->name('session.booking');
    Route::get('career/coaching', [CounsellorProfileController::class, 'main'])->name('career.main');
    Route::resource('payments', SessionPaymentController::class);
    Route::resource('profile', UserProfileController::class);
    Route::resource('session', UserCounsellorSessionController::class);
    // Route::post('session/started', [UserCounsellorSessionController::class, 'sessionStarted'])->name('session.started');
    Route::post('counsellor/available-sessions', [UserCounsellorSessionController::class, 'counsellorAvailableSessions'])->name('counsellor.available-sessions');
    Route::resource('professional', UserProfessionalController::class)->except('index', 'show');
    Route::resource('video-call', User\VideoCallController::class)->only(["show"]);
    Route::get("test/{id}/info", [PaymentInfoController::class, 'index'])->name("payments.info.index");
    Route::get('benefit/{word?}', [BenefitController::class, 'getData']);
    Route::POST('stripe/payment', [SessionPaymentController::class, 'stripePayment'])->name('stripe.payment');
    // Route::POST('session/payment', [SessionPaymentController::class, 'sessionPayment'])->name('session.payment');

    // coupon implementation
    Route::post('stripe/apply_coupon', [SessionPaymentController::class, 'apply_coupon_code'])->name('stripe.apply_coupon');

    Route::get('getCounsellor/{id}', [CounsellorProfileController::class, 'getCounsellor']);
    Route::get('reports', [User\SessionReportController::class, 'index'])->name("sessions.reports");
    Route::get('checkSession/{id}', [UserCounsellorSessionController::class, 'checkSession']);
    // Route::get('getCounsellorSessions', [CounsellorSessionController::class, 'getCounsellorSessions']);
    Route::get('test/{test}', [TestController::class, 'userTestsQuestions'])->name('test');
    Route::get('test/{test}/restart', [TestController::class, 'userTestRestart'])->name('test.restart');
    Route::post('results/store', [UserResultController::class, 'store'])->name('results.store');
    Route::get('result/report', [UserResultController::class, 'report'])->name("test.report"); // test report for user
    Route::get('test/{test}/instructions', [TestController::class, 'instructions'])->name('test.instructions');

    Route::get('personal-information/{user_id}/{test_name}', [UserPersonalInformationController::class, 'getUserInformation'])->name('user.family');
    // Route::get('personal-information/{status}',[UserPersonalInformationController::class,'getUserInformation']);
    Route::get('download-personality-result/{word?}', [DownloadResultController::class, 'personality'])->name('personality.test.download');
    Route::get('download-career-result', [DownloadResultController::class, 'career'])->name('career.test.download');
    Route::get('download-skill-assessment-result', [DownloadResultController::class, 'skill_assessment'])->name('skill-assessment.test.download');

    Route::POST('profile-picture', [UserController::class, 'updateUserProfilePicture']);
    Route::POST('password/change', [UserController::class, 'changePassword'])->name('password.change');

app/Http/Controllers/API/User/SessionReportController.php
<?php

namespace App\Http\Controllers\API\User;

use App\Http\Controllers\Controller;
use App\Http\Resources\User\SessionReportResource;
use App\Models\SessionReport;
use App\Models\UserCounsellorSession;
use Illuminate\Http\Request;

class SessionReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @return \Illuminate\Http\Response
     */
    public function create(UserCounsellorSession $session)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \Illuminate\Http\Request          $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, UserCounsellorSession $session)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function show(UserCounsellorSession $session, SessionReport $report)
    {
        return new SessionReportResource($report);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function edit(UserCounsellorSession $session, SessionReport $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request          $request
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UserCounsellorSession $session, SessionReport $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserCounsellorSession $session, SessionReport $report)
    {
        //
    }
}

app/Http/Controllers/Counsellor/UserController.php
<?php

namespace App\Http\Controllers\Counsellor;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\UserCounsellorSession;
use App\Models\UserPersonalInformation;
use App\Models\UserProfessional;
use App\Models\UserProfile;
use App\Models\UserResult;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show(User $user)
    {
        if (!$user->hasRole("User") || $user->hasRole("Super Admin")) {
            abort(404);
        }

        $personalityTestResults = $user->personalityTestResults();
        $sessions = $user->sessions();
        $userProfile = $user->profile;

        $familyInfo = $user->personalInformation('Personal');
        $familyInfo = $familyInfo[0]->answer ?? null;
        $careerAmbitions = $user->personalInformation('career');
        $reasonsForGettingJob = UserPersonalInformation::reasonsForGettingJob;
        $decision = $user->personalInformation('decision');
        $studyHabitsAndRoutine = $user->personalInformation('study_habits_and_routine') ?? null;
        $futureSelfReflection = $user->personalInformation('future_self_reflection') ?? null;
        $reasons = null;
        $forcast = null;
        if (count($futureSelfReflection)) {
            $forcast = (!is_array($futureSelfReflection[0]->answer)) ? "Other" : ($futureSelfReflection[0]->answer == "Working" ? "Working" : "Studying");
            if ($forcast == "Working") {
                $reasons = UserPersonalInformation::reasonsForWorking;
            } elseif ($forcast == "Studying") {
                $reasons = UserPersonalInformation::reasonsForStudying;
            }
        }

        return view(
            'counsellor.users.view',
            compact(
                "careerAmbitions",
                "decision",
                "familyInfo",
                "forcast",
                "futureSelfReflection",
                "personalityTestResults",
                "reasons",
                "reasonsForGettingJob",
                "sessions",
                "studyHabitsAndRoutine",
                "user",
                "userProfile",
            )
        );
    }

}

app/Http/Controllers/User/SessionReportController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\SessionReport;
use App\Models\UserCounsellorSession;
use Exception;
use Illuminate\Http\Request;

class SessionReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();
        $reports = $user->reports;

        return view('users.sessions.reports.index',
            compact(
                'reports',
            )
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($session_id)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function show(SessionReport $sessionReport)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function edit(SessionReport $sessionReport)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SessionReport $sessionReport)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function destroy(SessionReport $sessionReport)
    {
        //
    }
}

resources/views/admin/users/professional/edit.blade.php
@extends('layouts.admin',['pagename'=>'Edit Profile'])
@section('content')
<x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ __('Users') }}
    </h2>
</x-slot>

<div class="container bg-white px-4 py-4 rounded">
    <div class="row">
        <div class="col-12">
            <div class="main">
                <div class="floating"></div>
                <div class="p-0 p-lg-4">
                    <div class="card border-0 bg-transparent">
                        <div class="card-body">
                            <div class="inner p-3">
                                <form action="{{ route('admin.users.professional.update', $user->id) }}" id="editProfile" method="POST" class="row g-3 align-items-baseline">
                                    @csrf @method('PUT')
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">First Name</label>
                                            <input type="text" name="name" id="name" value="{{ $user->name }}" class="@error('name') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="last_name">Last Name</label>
                                            <input type="text" name="last_name" id="last_name" value="{{ $user->last_name }}" class="@error('last_name') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="email" name="email" id="email" value="{{ $user->email }}" class="@error('email') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="date_of_birth">Date of Birth </label>
                                            <input type="date" name="date_of_birth" id="date_of_birth" value="{{ date('Y-m-d', strtotime($userProfile->date_of_birth)) }}" class="@error('date_of_birth') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="city">City</label>
                                            <input name="city" id="city" value="{{ $userProfile->city }}" class="@error('city') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="experience">Experience</label>
                                            <input name="experience" id="experience" value="{{ $userProfile->experience }}" class="@error('experience') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="education_level">Education Level</label>
                                            <select name="education_level" id="education_level" class="@error('education_level') is-invalid @enderror form-select">
                                                <option value="">Please select your education level</option>
                                                <option {{ $userProfile->education_level == "Lower secondary" ? 'selected' : '' }}>Lower secondary</option>
                                                <option {{ $userProfile->education_level == "Upper secondary" ? 'selected' : '' }}>Upper secondary</option>
                                                <option {{ $userProfile->education_level == "Post-secondary" ? 'selected' : '' }}>Post-secondary</option>
                                                <option {{ $userProfile->education_level == "Bachelor's" ? 'selected' : '' }}>Bachelor's</option>
                                                <option {{ $userProfile->education_level == "Master's" ? 'selected' : '' }}>Master's</option>
                                                <option {{ $userProfile->education_level == "Doctorate" ? 'selected' : '' }}>Doctorate</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="organization_name">Organization Name</label>
                                            <input name="organization_name" id="organization_name" value="{{ $userProfile->organization_name }}" class="@error('organization_name') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="role">Role</label>
                                            <input name="role" id="role" value="{{ $userProfile->role }}" class="@error('role') is-invalid @enderror form-control">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="gender">Gender</label><br>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" @checked($user->gender=="Male") name="gender" type="radio" id="Male" value="Male">
                                                <label class="form-check-label" for="Male">Male</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" @checked($user->gender=="Female") name="gender" type="radio" id="Female" value="Female">
                                                <label class="form-check-label" for="Female">Female</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                                <input class="form-check-input" @checked($user->gender=="Other") name="gender" type="radio" id="Other" value="Other">
                                                <label class="form-check-label" for="Other">Other</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-3 mt-3">
                                        <a href="{{ url()->previous() }}" class="btn btn-secondary btn-sm">Cancel changes</a>
                                        <input type="submit" value="Save changes" class="btn btn-success btn-sm">
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ update profile -->
</div>
@endsection

resources/views/admin/users/professional/view.blade.php
@extends('layouts.admin',['pagename'=>'User Profile'])
@section('content')
<style>
    .progress {
        height: 1.5rem;
    }
</style>
<div class="container mb-5">
    <div class="row gy-3">
        <div class="col-12 col-lg-4">
            <div class="card h-100 shadow">
                <div class="card-body">
                    <div class="text-center">
                        <img class="rounded-circle border" src="{{ asset($user->profilePhoto) }}" alt="User profile picture" width="150" height="150">
                    </div>

                    <h3 class="text-center headingFont">{{ $user->fullName }}</h3>

                    <p class="text-muted text-center"><b>{{ $user->email }}</b></p>

                    {{-- <ul class="list-group">
                        <li class="list-group-item">
                            <b>D.O.B:</b> <span class="float-right">{{ $userProfile?->date_of_birth }}</span>
                        </li>
                        <li class="list-group-item">
                            <b>Country:</b> <span class="float-right">{{ $userProfile?->city }}</span>
                        </li>
                        <li class="list-group-item">
                            <b>Experience:</b> <span class="float-right">{{ $userProfile?->experience }}</span>
                        </li>
                        <li class="list-group-item">
                            <b>Education level:</b> <span class="float-right">{{ $userProfile?->education_level }}</span>
                        </li>
                        <li class="list-group-item">
                            <b>Organization working in:</b> <span class="float-right">{{ $userProfile?->organization_name }}</span>
                        </li>
                        <li class="list-group-item">
                            <b>Role:</b> <span class="float-right">{{ $userProfile?->role }}</span>
                        </li>
                    </ul> --}}
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-8">
            <div class="card h-100 shadow">
                <div class="card-body">
                    <table class="table table-striped" id="example1">
                        <thead> <strong> User's Sessions </strong>
                            <tr>
                                <th>#</th>
                                <th>Counsellor</th>
                                <th>Date </th>
                                <th>Time</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($sessions as $key=>$session)
                            <tr>
                                <td>{{ ++$key }}</td>
                                <td>
                                    <a href="{{ route("admin.counsellors.show", $session->counsellor->id) }}">{{ $session->counsellor->fullname }}</a>
                                </td>
                                <td>{{ date("d-m-Y", strtotime($session->session->session_timing)) }}</td>
                                <td>{{ date("h:i A", strtotime($session->session->session_timing)) }}</td>
                                <td>{!! $session->session_status !!}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card shadow h-100">
                <div class="h4 rounded-top headingFont text-center text-white py-3" style="background-color: #3ab3f8 !important;">
                    PERSONALITY TEST RESULTS
                </div>
                <div class="card-body px-lg-5">
                    @if($personalityTestResults > 99)
                        @include("admin.users.results.personality")
                    @elseif($personalityTestResults < 1)
                        Not attempted yet
                    @else
                        Not completed yet
                    @endif
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card h-100 shadow">
                <div class="h4 rounded-top headingFont text-white text-center py-3" style="background-color: #ffc854 !important">
                    CAREER EXPECTATIONS QUESTIONNAIRE
                </div>
                <div class="card-body px-lg-5">
                    @if($careerExpectationsTestResults > 99)
                        @include("admin.users.results.career-expectations")
                    @elseif($careerExpectationsTestResults < 1)
                        Not attempted yet
                    @else
                        Not completed yet
                    @endif
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="card h-100 shadow">
                <div class="h4 rounded-top headingFont text-center text-white py-3" style="background-color: #fe7852 !important;">SKILL ASSESSMENT TEST RESULTS</div>
                <div class="card-body px-lg-5">
                    @if($skillAssessmentTestResults > 99)
                        @include("admin.users.results.skill-assessment")
                    @elseif($skillAssessmentTestResults < 1)
                        Not attempted yet
                    @else
                        Not completed yet
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection