routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BenefitController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\Counsellor;
use App\Http\Controllers\CounsellorProfileController;
use App\Http\Controllers\CounsellorSessionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DownloadResultController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InstructionController;
use App\Http\Controllers\PaymentInfoController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SessionPaymentController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\User;
use App\Http\Controllers\UserCounsellorSessionController;
use App\Http\Controllers\UserPersonalInformationController;
use App\Http\Controllers\UserProfessionalController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserResultController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use App\Http\Controllers\User\VerifyPhoneController;
use App\Http\Controllers\UserTimezoneController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('coach/register', [AuthController::class, 'counsellorRegistration'])->name("coach.apply");
Route::view('coach/apply', 'counsellor.apply')->name('counsellor.apply');
Route::get('faqs', [FrontController::class, "faqs"])->name('faqs');
// Route::get('help', [FrontController::class, 'help'])->name('help');

Route::get('about', [FrontController::class, 'about'])->name('about');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::resource('contact-us', ContactUsController::class)->only(["store"]);

Route::get('counsellor-register', [AuthController::class, 'counsellorRegister']);
Route::post('counsellor-registration', [AuthController::class, 'counsellorRegister'])->name('counsellorRegister');
Route::get('school', [FrontController::class, 'school'])->name("school");
Route::get('register/{profession}', [AuthController::class, 'register']);
// added routes for new design
Route::get('get-started', [AuthController::class, 'new_signup'])->name('who-are-you');

// Route::get('get-started', [FrontController::class, 'getStarted'])->name('who-are-you');
Route::get('university', [FrontController::class, 'university'])->name("university");
Route::get('Professional', [FrontController::class, 'professional'])->name("professional");
Route::get('Parents', [FrontController::class, 'parent'])->name("parents");
Route::get('benefit/{word?}', [BenefitController::class, 'getData'])->name('benefit')->middleware(["auth", "verified"]);

Route::group(
    ['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Super Admin']],
    function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('users', Admin\UserController::class);
        Route::resource('users.professional', Admin\UserProfessionalController::class);
        Route::resource('counsellors', Admin\CounsellorController::class);
        Route::resource('tests', TestController::class);
        Route::resource('questions', QuestionController::class);
        Route::resource('payments', Admin\SessionPaymentController::class)->except(["edit", "create"]);
        Route::resource('benefits', BenefitController::class);
        Route::resource('instructions', InstructionController::class);
        Route::resource('videos', Admin\VideoController::class);
        Route::resource('faqs', FaqController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::get('changeCouponStatus', [Admin\CouponController::class, 'changeCouponStatus'])->name('coupons.changeCouponStatus');
        Route::get('changeUserStatus', [Admin\UserController::class, 'changeUserStatus'])->name('users.changeUserStatus');
        Route::get('users/{id}/change-password', [Admin\UserController::class, 'changeUserPassword'])->name('users.changeUserPassword');
        Route::post('users/{id}/update-password', [Admin\UserController::class, 'updateUserPassword'])->name('users.updateUserPassword');
        Route::get('currencies', [Admin\CurrencyController::class, 'index'])->name('currencies.index');
        Route::post('currencies/store', [Admin\CurrencyController::class, 'store'])->name('currencies.store');
        Route::get('currencies/{id}/edit', [Admin\CurrencyController::class, 'edit'])->name('currencies.edit');
        Route::put('currencies/update', [Admin\CurrencyController::class, 'update'])->name('currencies.update');
        Route::delete('currencies/{id}/delete', [Admin\CurrencyController::class, 'destroy'])->name('currencies.destroy');
        Route::get('deleted/users', [Admin\TrashedUsersController::class, 'deletedUsers'])->name('trashedUsers');
        Route::delete('deleted/users/{id}', [Admin\TrashedUsersController::class, 'deletePermanently'])->name('trashedUsers.delete');
        Route::get('deleted/coaches', [Admin\TrashedUsersController::class, 'deletedCoaches'])->name('counsellors.trashed');
        Route::get('restore/users/{id}', [Admin\TrashedUsersController::class, 'restore'])->name('users.restore');
    }
);

Route::middleware(['verified', 'auth', 'change_password'])->group(function () {
    Route::get('dashboard', [DashboardController::class, "dashboard"])->name('dashboard');
    Route::get('help', [FrontController::class, 'help'])->name('help');
    Route::POST('help', [FrontController::class, 'helpStore'])->name('help.store');
    Route::POST('user/{id}/timezone/update', [UserTimezoneController::class, 'updateUserTimezone'])->name('user.timezone.update');
});

Route::get('refresh_captcha', [FrontController::class, 'refreshCaptcha']);
Route::post('subscribe', [SubscribeController::class, 'store'])->name('subscribe');
Route::prefix("user")->as("user.")->middleware(['auth', 'verified', 'role:User'])->group(function () {
    Route::POST('connect-zoom', [UserController::class, 'connectZoomAccount'])->name("zoom.account.connect");
    Route::get('session/booking', [CounsellorProfileController::class, 'index'])->name('session.booking');
    Route::get('career/coaching', [CounsellorProfileController::class, 'main'])->name('career.main');
    Route::resource('payments', SessionPaymentController::class);
    Route::resource('profile', UserProfileController::class);
    Route::resource('session', UserCounsellorSessionController::class);
    // Route::post('session/started', [UserCounsellorSessionController::class, 'sessionStarted'])->name('session.started');
    Route::post('counsellor/available-sessions', [UserCounsellorSessionController::class, 'counsellorAvailableSessions'])->name('counsellor.available-sessions');
    Route::resource('professional', UserProfessionalController::class)->except('index', 'show');
    Route::resource('video-call', User\VideoCallController::class)->only(["show"]);
    Route::get("test/{id}/info", [PaymentInfoController::class, 'index'])->name("payments.info.index");
    Route::get('benefit/{word?}', [BenefitController::class, 'getData']);
    Route::POST('stripe/payment', [SessionPaymentController::class, 'stripePayment'])->name('stripe.payment');
    // Route::POST('session/payment', [SessionPaymentController::class, 'sessionPayment'])->name('session.payment');

    // coupon implementation
    Route::post('stripe/apply_coupon', [SessionPaymentController::class, 'apply_coupon_code'])->name('stripe.apply_coupon');

    Route::get('getCounsellor/{id}', [CounsellorProfileController::class, 'getCounsellor']);
    Route::get('reports', [User\SessionReportController::class, 'index'])->name("sessions.reports");
    Route::get('checkSession/{id}', [UserCounsellorSessionController::class, 'checkSession']);
    // Route::get('getCounsellorSessions', [CounsellorSessionController::class, 'getCounsellorSessions']);
    Route::get('test/{test}', [TestController::class, 'userTestsQuestions'])->name('test');
    Route::get('test/{test}/restart', [TestController::class, 'userTestRestart'])->name('test.restart');
    Route::post('results/store', [UserResultController::class, 'store'])->name('results.store');
    Route::get('result/report', [UserResultController::class, 'report'])->name("test.report"); // test report for user
    Route::get('test/{test}/instructions', [TestController::class, 'instructions'])->name('test.instructions');

    Route::get('personal-information/{user_id}/{test_name}', [UserPersonalInformationController::class, 'getUserInformation'])->name('user.family');
    // Route::get('personal-information/{status}',[UserPersonalInformationController::class,'getUserInformation']);
    Route::get('download-personality-result/{word?}', [DownloadResultController::class, 'personality'])->name('personality.test.download');
    Route::get('download-career-result', [DownloadResultController::class, 'career'])->name('career.test.download');
    Route::get('download-skill-assessment-result', [DownloadResultController::class, 'skill_assessment'])->name('skill-assessment.test.download');

    Route::POST('profile-picture', [UserController::class, 'updateUserProfilePicture']);
    Route::POST('password/change', [UserController::class, 'changePassword'])->name('password.change');

app/Http/Controllers/Admin/CounsellorController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreCounsellorProfileRequest;
use App\Http\Requests\Counsellor\StoreFirstTimePasswordResetRequest;
use App\Models\Country;
use App\Models\User;
use App\Traits\GenericTrait;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

class CounsellorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $counsellors = User::latestCounsellors();
        return view(
            'admin.counsellors.index',
            compact(
                'counsellors',
            )
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.counsellors.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreCounsellorProfileRequest $request)
    {
        // get validated data
        $validated = $request->validated();

        // verfiy counsellor by default
        $validated["email_verified_at"] = now();
        $validated["name"]              = $validated["first_name"];
        $validated["password"]          = Hash::make($validated["password"]);

        $inputDomain = $validated['linked_in'];
        // Check if the input domain starts with "http://" or "https://"
        if (strpos($inputDomain, "http://") === 0 || strpos($inputDomain, "https://") === 0) {
            $validated['linked_in'] = $inputDomain;
        } else {
            $validated['linked_in'] = "https://" . $inputDomain;
        }

        // create counsellor account
        $counsellor =  User::create($validated);

        // assign a role
        $role = Role::where('name', 'Counsellor')->first();
        $counsellor->assignRole($role->name);

        // create counsellor profile
        $profile = $counsellor->profile()->create($validated);


        // send verification email
        // $user->sendEmailVerificationNotification();
        // toastr()->success('Registration completed, Please verify your email to continue.');
        toastr()->success("Coach profile successfully.");
        return redirect()->route("admin.counsellors.index");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $counsellor)
    {
        if (! $counsellor->hasRole("Counsellor")) {
            abort(404);
        }

        $sessions = $counsellor->sessions();
        $connectedUsers = $counsellor->recentlyRegisteredSessions(null);
        return view(
            "admin.counsellors.view",
            compact(
                "counsellor",
                "connectedUsers",
                "sessions",
            )
        );
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $counsellor)
    {
        if (! $counsellor->hasRole("Counsellor")) {
            abort(404);
        }
        $countries = Country::names();
        // dd($counsellorProfile);
        return response()->view('admin.counsellors.edit',
            compact(
                'counsellor',
                'countries',
            )
        );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\Models\User         $user
     * @return \Illuminate\Http\Response
     */

    public function update(Request $request, User $counsellor)
    {
        // validate input data...
        $validated = $request->validate([
            'name' => 'required',
            'last_name'  => 'required',
            'email' => ['required', 'email', 'max:255', 'unique:users,email,' . $counsellor->id],
        ]);

        // update personal data
        $counsellor->update($validated);
        $counsellor->profile->update([
            'country' => $request->country,
        ]);

        toastr()->success('Counsellor Information Updated');
        return redirect()->route('admin.counsellors.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        //
    }

    public function changePassword()
    {
        return view("counsellor.reset-password");
    }

    public function updatePassword(StoreFirstTimePasswordResetRequest $request)
    {
        $validated = $request->validated();

        $counsellor = Auth::user();
        $counsellor->password = Hash::make($validated["password"]);
        $counsellor->password_changed = true;
        $counsellor->save();
        toastr()->success("Password updated successfully.");
        return redirect()->route("dashboard");
    }
}

app/Http/Controllers/Counsellor/UserController.php
<?php

namespace App\Http\Controllers\Counsellor;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\UserCounsellorSession;
use App\Models\UserPersonalInformation;
use App\Models\UserProfessional;
use App\Models\UserProfile;
use App\Models\UserResult;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show(User $user)
    {
        if (!$user->hasRole("User") || $user->hasRole("Super Admin")) {
            abort(404);
        }

        $personalityTestResults = $user->personalityTestResults();
        $sessions = $user->sessions();
        $userProfile = $user->profile;

        $familyInfo = $user->personalInformation('Personal');
        $familyInfo = $familyInfo[0]->answer ?? null;
        $careerAmbitions = $user->personalInformation('career');
        $reasonsForGettingJob = UserPersonalInformation::reasonsForGettingJob;
        $decision = $user->personalInformation('decision');
        $studyHabitsAndRoutine = $user->personalInformation('study_habits_and_routine') ?? null;
        $futureSelfReflection = $user->personalInformation('future_self_reflection') ?? null;
        $reasons = null;
        $forcast = null;
        if (count($futureSelfReflection)) {
            $forcast = (!is_array($futureSelfReflection[0]->answer)) ? "Other" : ($futureSelfReflection[0]->answer == "Working" ? "Working" : "Studying");
            if ($forcast == "Working") {
                $reasons = UserPersonalInformation::reasonsForWorking;
            } elseif ($forcast == "Studying") {
                $reasons = UserPersonalInformation::reasonsForStudying;
            }
        }

        return view(
            'counsellor.users.view',
            compact(
                "careerAmbitions",
                "decision",
                "familyInfo",
                "forcast",
                "futureSelfReflection",
                "personalityTestResults",
                "reasons",
                "reasonsForGettingJob",
                "sessions",
                "studyHabitsAndRoutine",
                "user",
                "userProfile",
            )
        );
    }

}

resources/views/admin/counsellors/edit.blade.php
@extends('layouts.admin', ['pagename' => 'User Profile'])
@section('content')
    <style>
        .saveChanger:hover {
            background-color: #06acf4 !important;
        }

        .cancelChanger:hover {
            background-color: black !important;
        }

        .deleteChanger:hover {
            background-color: red !important;
        }
    </style>
    <div class="container-fluid px-0">
        <div class="row g-0">
            <div class="col-12">
                <div class="p-3 main h-100">
                    <div class="floating"></div>
                    <form action="{{ route('admin.counsellors.update', $counsellor) }}" class="needs-validation" novalidate
                        method="post">
                        @csrf
                        @method('PUT')
                        <div class="inner card">
                            <div class="card-body">
                                <div class="row g-3">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="name">First Name</label>
                                            <input type="text" name="name"
                                                value="{{ old('name') ?? $counsellor->first_name }}"
                                                class="form-control @error('name') is-invalid @enderror" required>
                                            <div class="invalid-feedback">Please fill in this field.</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="last_name">Last Name</label>
                                            <input type="text" name="last_name"
                                                value="{{ old('last_name') ?? $counsellor->last_name }}"
                                                class="form-control @error('last_name') is-invalid @enderror"
                                                required>
                                            <div class="invalid-feedback">Please fill in this field.</div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="email">Email</label>
                                            <input type="email" name="email"
                                                value="{{ old('email') ?? $counsellor?->email }}"
                                                class="form-control @error('email') is-invalid @enderror" required>
                                            <div class="invalid-feedback">Please fill in this field.</div>
                                        </div>
                                    </div>

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label for="country">Country</label>
                                            <select name="country"
                                                class="form-select @error('country') is-invalid @enderror" required>
                                                <option value="">Please select your country</option>
                                                @foreach ($countries as $country)
                                                    <option @selected($country == (old('country') ?? $counsellor->profile->country))>{{ $country }}
                                                    </option>
                                                @endforeach
                                            </select>
                                            <div class="invalid-feedback">Please fill in this field.</div>
                                        </div>
                                    </div>

                                    <div class="col-md-12 d-flex justify-content-start">
                                        <a class="btn btn-secondary text-white me-2 cancelChanger"
                                            href="{{ url()->previous() }}">Cancel Changes</a>
                                        <button class="btn btn-primary">Save Changes</button>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/counsellors/index.blade.php
@extends('layouts.admin',['pagename'=>'Coaches'])
@section('content')
<x-slot name="header">
    <h2 class="font-semibold text-xl text-gray-800 leading-tight">
        {{ __('Coaches') }}
    </h2>
</x-slot>
<div class="container bg-white shadow px-4 py-4 rounded">
    <div class="row">
        <div class="col-md-12 justify-content-end">
            <a href="{{ route("admin.counsellors.create") }}" class="btn btn-primary" data-bs-toggle="tooltip" data-bs-title="Create Coach Profile">
                <i class="fa fa-solid fa-plus"></i>
            </a>
            <a href="{{ route("admin.counsellors.trashed") }}" class="btn btn-danger">
                {{-- <i class="fa fa-solid fa-plus"></i> --}}
                Deleted Records
            </a>
        </div>
        <div class="col-md-12">
            <table class="table table-striped" id="example1">
                <thead>
                    <tr>
                        <td>#</td>
                        <td>Name</td>
                        <td>Email</td>
                        <td>Action</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($counsellors as $key => $counsellor)
                    <tr>
                        <td>{{ ++$key }}</td>
                        <td>{{ $counsellor->fullname }}</td>
                        <td>{{ $counsellor->email }}</td>
                        <td>
                            <div class="btn-group btn-group-sm" role="group" aria-label="Actions">
                                <a href="{{ route("admin.counsellors.show", $counsellor->id) }}" title="view profile" data-bs-toggle="tooltip" class="btn btn-outline-success">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a type="button" class="btn btn-outline-secondary" title="edit profile" data-bs-toggle="tooltip" href="{{ route("admin.counsellors.edit", $counsellor->id) }}">
                                    <i class="fa fa-pencil"></i>
                                </a>
                                {{-- <a type="button" class="btn btn-outline-primary" href="{{ route('admin.user.password',$counsellor->id) }}" title="change password" data-bs-toggle="tooltip">
                                    <i class="fa fa-key"></i>
                                </a> --}}
                                <button type="submit" class="btn btn-outline-danger" data-bs-toggle="modal" data-bs-target="#deleteUser{{ $counsellor->id }}Modal">
                                    <i class="fa fa-trash"></i>
                                </button>
                            </div>
                            <div class="modal fade" id="deleteUser{{ $counsellor->id }}Modal" data-bs-backdrop="static" data-bs-keyboard="true" tabindex="-1" aria-labelledby="deleteUser{{ $counsellor->id }}ModalLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h1 class="modal-title fs-5" id="deleteUser{{ $counsellor->id }}ModalLabel">Attention!</h1>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <form action="{{ route('admin.users.destroy', $counsellor->id) }}" method="post">
                                            @csrf @method('DELETE')
                                            <div class="modal-body">
                                                Are you sure you want to delete this coach?
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">No</button>
                                                <button type="submit" class="btn btn-sm btn-danger">Yes</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
<!-- Add new counsellor modal -->
@section('modal')
<form action="" class="needs-validation" id="add_counsellor" class="needs-validation" novalidate method="post">
    @csrf
    <div class="modal-body">
        <div class="row">
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" name="first_name" id="first_name" required placeholder="first name">
                    <label for="first_name">First name</label>
                    <div class="invalid-feedback">First name can't be empty.</div>
                    <div class="valid-feedback">Looks good.</div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" name="first_name" id="last_name" required placeholder="last name">
                    <label for="last_name">Last name</label>
                    <div class="invalid-feedback">Last name can't be empty.</div>
                    <div class="valid-feedback">Looks good!</div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="text" class="form-control" name="email" id="email" required placeholder="email address">
                    <label for="email">Email address</label>
                    <div class="invalid-feedback">Email address can't be empty.</div>
                    <div class="valid-feedback">Looks good!</div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="date" class="form-control" name="date_of_birth" id="date_of_birth" required placeholder="date of birth">
                    <label for="date_of_birth">Date of Birth</label>
                    <div class="invalid-feedback">Date of Birth can't be empty.</div>
                    <div class="valid-feedback">Looks good!</div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" name="password" id="password" required placeholder="Password">
                    <label for="password">Password</label>
                    <div class="invalid-feedback">Password can't be empty.</div>
                    <div class="valid-feedback">Looks good!</div>
                </div>
            </div>
            <div class="col-12 col-md-6">
                <div class="form-floating mb-3">
                    <input type="password" class="form-control" name="confirm_password" id="confirm_password" required placeholder="Confirm Password">
                    <label for="confirm_password">Confirm password</label>
                    <div class="invalid-feedback">Please confirm password.</div>
                    <div class="valid-feedback">Looks good!</div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="bg-secondary btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" form="add_counsellor">Add Counsellor</button>
    </div>
</form>
@endsection
@include('extra.modal',['modal_title'=>'Add New Counsellor'])
@endsection