routes/web.php
<?php

use App\Http\Controllers\Admin;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BenefitController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\Counsellor;
use App\Http\Controllers\CounsellorProfileController;
use App\Http\Controllers\CounsellorSessionController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DownloadResultController;
use App\Http\Controllers\FaqController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InstructionController;
use App\Http\Controllers\PaymentInfoController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\QuestionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SessionPaymentController;
use App\Http\Controllers\SubscribeController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\User;
use App\Http\Controllers\UserCounsellorSessionController;
use App\Http\Controllers\UserPersonalInformationController;
use App\Http\Controllers\UserProfessionalController;
use App\Http\Controllers\UserProfileController;
use App\Http\Controllers\UserResultController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\View;
use App\Http\Controllers\User\VerifyPhoneController;
use App\Http\Controllers\UserTimezoneController;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('coach/register', [AuthController::class, 'counsellorRegistration'])->name("coach.apply");
Route::view('coach/apply', 'counsellor.apply')->name('counsellor.apply');
Route::get('faqs', [FrontController::class, "faqs"])->name('faqs');
// Route::get('help', [FrontController::class, 'help'])->name('help');

Route::get('about', [FrontController::class, 'about'])->name('about');
Route::get('contact', [FrontController::class, 'contact'])->name('contact');
Route::resource('contact-us', ContactUsController::class)->only(["store"]);

Route::get('counsellor-register', [AuthController::class, 'counsellorRegister']);
Route::post('counsellor-registration', [AuthController::class, 'counsellorRegister'])->name('counsellorRegister');
Route::get('school', [FrontController::class, 'school'])->name("school");
Route::get('register/{profession}', [AuthController::class, 'register']);
// added routes for new design
Route::get('get-started', [AuthController::class, 'new_signup'])->name('who-are-you');

// Route::get('get-started', [FrontController::class, 'getStarted'])->name('who-are-you');
Route::get('university', [FrontController::class, 'university'])->name("university");
Route::get('Professional', [FrontController::class, 'professional'])->name("professional");
Route::get('Parents', [FrontController::class, 'parent'])->name("parents");
Route::get('benefit/{word?}', [BenefitController::class, 'getData'])->name('benefit')->middleware(["auth", "verified"]);

Route::group(
    ['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'role:Super Admin']],
    function () {
        Route::resource('roles', RoleController::class);
        Route::resource('permissions', PermissionController::class);
        Route::resource('users', Admin\UserController::class);
        Route::resource('users.professional', Admin\UserProfessionalController::class);
        Route::resource('counsellors', Admin\CounsellorController::class);
        Route::resource('tests', TestController::class);
        Route::resource('questions', QuestionController::class);
        Route::resource('payments', Admin\SessionPaymentController::class)->except(["edit", "create"]);
        Route::resource('benefits', BenefitController::class);
        Route::resource('instructions', InstructionController::class);
        Route::resource('videos', Admin\VideoController::class);
        Route::resource('faqs', FaqController::class);
        Route::resource('coupons', Admin\CouponController::class);
        Route::get('changeCouponStatus', [Admin\CouponController::class, 'changeCouponStatus'])->name('coupons.changeCouponStatus');
        Route::get('changeUserStatus', [Admin\UserController::class, 'changeUserStatus'])->name('users.changeUserStatus');
        Route::get('users/{id}/change-password', [Admin\UserController::class, 'changeUserPassword'])->name('users.changeUserPassword');
        Route::post('users/{id}/update-password', [Admin\UserController::class, 'updateUserPassword'])->name('users.updateUserPassword');
        Route::get('currencies', [Admin\CurrencyController::class, 'index'])->name('currencies.index');
        Route::post('currencies/store', [Admin\CurrencyController::class, 'store'])->name('currencies.store');
        Route::get('currencies/{id}/edit', [Admin\CurrencyController::class, 'edit'])->name('currencies.edit');
        Route::put('currencies/update', [Admin\CurrencyController::class, 'update'])->name('currencies.update');
        Route::delete('currencies/{id}/delete', [Admin\CurrencyController::class, 'destroy'])->name('currencies.destroy');
        Route::get('deleted/users', [Admin\TrashedUsersController::class, 'deletedUsers'])->name('trashedUsers');
        Route::delete('deleted/users/{id}', [Admin\TrashedUsersController::class, 'deletePermanently'])->name('trashedUsers.delete');
        Route::get('deleted/coaches', [Admin\TrashedUsersController::class, 'deletedCoaches'])->name('counsellors.trashed');
        Route::get('restore/users/{id}', [Admin\TrashedUsersController::class, 'restore'])->name('users.restore');
    }
);

Route::middleware(['verified', 'auth', 'change_password'])->group(function () {
    Route::get('dashboard', [DashboardController::class, "dashboard"])->name('dashboard');
    Route::get('help', [FrontController::class, 'help'])->name('help');
    Route::POST('help', [FrontController::class, 'helpStore'])->name('help.store');
    Route::POST('user/{id}/timezone/update', [UserTimezoneController::class, 'updateUserTimezone'])->name('user.timezone.update');
});

Route::get('refresh_captcha', [FrontController::class, 'refreshCaptcha']);
Route::post('subscribe', [SubscribeController::class, 'store'])->name('subscribe');
Route::prefix("user")->as("user.")->middleware(['auth', 'verified', 'role:User'])->group(function () {
    Route::POST('connect-zoom', [UserController::class, 'connectZoomAccount'])->name("zoom.account.connect");
    Route::get('session/booking', [CounsellorProfileController::class, 'index'])->name('session.booking');
    Route::get('career/coaching', [CounsellorProfileController::class, 'main'])->name('career.main');
    Route::resource('payments', SessionPaymentController::class);
    Route::resource('profile', UserProfileController::class);
    Route::resource('session', UserCounsellorSessionController::class);
    // Route::post('session/started', [UserCounsellorSessionController::class, 'sessionStarted'])->name('session.started');
    Route::post('counsellor/available-sessions', [UserCounsellorSessionController::class, 'counsellorAvailableSessions'])->name('counsellor.available-sessions');
    Route::resource('professional', UserProfessionalController::class)->except('index', 'show');
    Route::resource('video-call', User\VideoCallController::class)->only(["show"]);
    Route::get("test/{id}/info", [PaymentInfoController::class, 'index'])->name("payments.info.index");
    Route::get('benefit/{word?}', [BenefitController::class, 'getData']);
    Route::POST('stripe/payment', [SessionPaymentController::class, 'stripePayment'])->name('stripe.payment');
    // Route::POST('session/payment', [SessionPaymentController::class, 'sessionPayment'])->name('session.payment');

    // coupon implementation
    Route::post('stripe/apply_coupon', [SessionPaymentController::class, 'apply_coupon_code'])->name('stripe.apply_coupon');

    Route::get('getCounsellor/{id}', [CounsellorProfileController::class, 'getCounsellor']);
    Route::get('reports', [User\SessionReportController::class, 'index'])->name("sessions.reports");
    Route::get('checkSession/{id}', [UserCounsellorSessionController::class, 'checkSession']);
    // Route::get('getCounsellorSessions', [CounsellorSessionController::class, 'getCounsellorSessions']);
    Route::get('test/{test}', [TestController::class, 'userTestsQuestions'])->name('test');
    Route::get('test/{test}/restart', [TestController::class, 'userTestRestart'])->name('test.restart');
    Route::post('results/store', [UserResultController::class, 'store'])->name('results.store');
    Route::get('result/report', [UserResultController::class, 'report'])->name("test.report"); // test report for user
    Route::get('test/{test}/instructions', [TestController::class, 'instructions'])->name('test.instructions');

    Route::get('personal-information/{user_id}/{test_name}', [UserPersonalInformationController::class, 'getUserInformation'])->name('user.family');
    // Route::get('personal-information/{status}',[UserPersonalInformationController::class,'getUserInformation']);
    Route::get('download-personality-result/{word?}', [DownloadResultController::class, 'personality'])->name('personality.test.download');
    Route::get('download-career-result', [DownloadResultController::class, 'career'])->name('career.test.download');
    Route::get('download-skill-assessment-result', [DownloadResultController::class, 'skill_assessment'])->name('skill-assessment.test.download');

    Route::POST('profile-picture', [UserController::class, 'updateUserProfilePicture']);
    Route::POST('password/change', [UserController::class, 'changePassword'])->name('password.change');

app/Http/Controllers/API/User/SessionReportController.php
<?php

namespace App\Http\Controllers\API\User;

use App\Http\Controllers\Controller;
use App\Http\Resources\User\SessionReportResource;
use App\Models\SessionReport;
use App\Models\UserCounsellorSession;
use Illuminate\Http\Request;

class SessionReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @return \Illuminate\Http\Response
     */
    public function create(UserCounsellorSession $session)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \Illuminate\Http\Request          $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, UserCounsellorSession $session)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function show(UserCounsellorSession $session, SessionReport $report)
    {
        return new SessionReportResource($report);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function edit(UserCounsellorSession $session, SessionReport $report)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request          $request
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, UserCounsellorSession $session, SessionReport $report)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\UserCounsellorSession $session
     * @param  \App\Models\SessionReport         $report
     * @return \Illuminate\Http\Response
     */
    public function destroy(UserCounsellorSession $session, SessionReport $report)
    {
        //
    }
}

app/Http/Controllers/Counsellor/UserController.php
<?php

namespace App\Http\Controllers\Counsellor;

use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\UserCounsellorSession;
use App\Models\UserPersonalInformation;
use App\Models\UserProfessional;
use App\Models\UserProfile;
use App\Models\UserResult;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function show(User $user)
    {
        if (!$user->hasRole("User") || $user->hasRole("Super Admin")) {
            abort(404);
        }

        $personalityTestResults = $user->personalityTestResults();
        $sessions = $user->sessions();
        $userProfile = $user->profile;

        $familyInfo = $user->personalInformation('Personal');
        $familyInfo = $familyInfo[0]->answer ?? null;
        $careerAmbitions = $user->personalInformation('career');
        $reasonsForGettingJob = UserPersonalInformation::reasonsForGettingJob;
        $decision = $user->personalInformation('decision');
        $studyHabitsAndRoutine = $user->personalInformation('study_habits_and_routine') ?? null;
        $futureSelfReflection = $user->personalInformation('future_self_reflection') ?? null;
        $reasons = null;
        $forcast = null;
        if (count($futureSelfReflection)) {
            $forcast = (!is_array($futureSelfReflection[0]->answer)) ? "Other" : ($futureSelfReflection[0]->answer == "Working" ? "Working" : "Studying");
            if ($forcast == "Working") {
                $reasons = UserPersonalInformation::reasonsForWorking;
            } elseif ($forcast == "Studying") {
                $reasons = UserPersonalInformation::reasonsForStudying;
            }
        }

        return view(
            'counsellor.users.view',
            compact(
                "careerAmbitions",
                "decision",
                "familyInfo",
                "forcast",
                "futureSelfReflection",
                "personalityTestResults",
                "reasons",
                "reasonsForGettingJob",
                "sessions",
                "studyHabitsAndRoutine",
                "user",
                "userProfile",
            )
        );
    }

}

app/Http/Controllers/User/SessionReportController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use App\Models\SessionReport;
use App\Models\UserCounsellorSession;
use Exception;
use Illuminate\Http\Request;

class SessionReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = auth()->user();
        $reports = $user->reports;

        return view('users.sessions.reports.index',
            compact(
                'reports',
            )
        );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($session_id)
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function show(SessionReport $sessionReport)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function edit(SessionReport $sessionReport)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, SessionReport $sessionReport)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\SessionReport $sessionReport
     * @return \Illuminate\Http\Response
     */
    public function destroy(SessionReport $sessionReport)
    {
        //
    }
}

resources/views/users/zoom/connect.blade.php
<form action="{{ route("user.zoom.account.connect") }}" method="post" onsubmit="this.querySelector('button').setAttribute('disabled', true);">
    @csrf
    <button class="btn w-100 btn-primary" data-bs-toggle="tooltip" data-bs-title="Connect zoom account to attend sessions.">
        Connect Zoom
    </button>
</form>

resources/views/users/zoom/meeting.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <title>Zoom Meeting SDK Sample JavaScript</title>

    <!-- For Client View -->
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.15.2/css/bootstrap.css" />
    <link type="text/css" rel="stylesheet" href="https://source.zoom.us/2.15.2/css/react-select.css" />

    <!-- Origin Trials to enable Gallery View in Chrome/Edge -->
    <!-- More Info: https://developers.zoom.us/docs/meeting-sdk/web/gallery-view/ -->
    <!-- SharedArrayBuffers in non-isolated pages on Desktop platforms -->
    <meta http-equiv="origin-trial" content="">

    <style>
        html,
        body {
            min-width: 0 !important;
        }

        #zmmtg-root {
            display: none;
        }

        main {
            width: 70%;
            margin: auto;
            text-align: center;
        }

        main button {
            margin-top: 20px;
            background-color: #2D8CFF;
            color: #ffffff;
            text-decoration: none;
            padding-top: 10px;
            padding-bottom: 10px;
            padding-left: 40px;
            padding-right: 40px;
            display: inline-block;
            border-radius: 10px;
            cursor: pointer;
            border: none;
            outline: none;
        }

        main button:hover {
            background-color: #2681F2;
        }
    </style>
</head>

<body>

    <main>
        <h1>FIND ME CAREER - Zoom One on One Session</h1>

        <!-- For Component View -->
        <div id="meetingSDKElement">
            <!-- Zoom Meeting SDK Rendered Here -->
        </div>

        {{-- <button onclick="getSignature()">Join Meeting</button> --}}
        <button onclick="startMeeting()">Join Session</button>
    </main>

    <!-- For Component and Client View -->
    <script src="https://source.zoom.us/2.15.2/lib/vendor/react.min.js"></script>
    <script src="https://source.zoom.us/2.15.2/lib/vendor/react-dom.min.js"></script>
    <script src="https://source.zoom.us/2.15.2/lib/vendor/redux.min.js"></script>
    <script src="https://source.zoom.us/2.15.2/lib/vendor/redux-thunk.min.js"></script>
    <script src="https://source.zoom.us/2.15.2/lib/vendor/lodash.min.js"></script>

    <!-- For Client View -->
    {{-- <script src="https://source.zoom.us/zoom-meeting-2.16.0.min.js"></script> --}}
    <script src="https://source.zoom.us/zoom-meeting-2.15.2.min.js"></script>
    <script>
        ZoomMtg.setZoomJSLib('https://source.zoom.us/2.15.2/lib', '/av')

        ZoomMtg.preLoadWasm()
        ZoomMtg.prepareWebSDK()
        // loads language files, also passes any error messages to the ui
        ZoomMtg.i18n.load('en-US')
        ZoomMtg.i18n.reload('en-US')

        // var authEndpoint = 'https://c3d1-2407-d000-503-e1c1-dd8b-2ffb-fdd8-2cac.ngrok-free.app/testjwttoken';
        var sdkKey = '{{ getenv('ZOOM_SDK_ID') }}';
        var meetingNumber = '{{ $videoCall->meeting_id }}';
        var passWord = 'secret1234';
        var role = {{ $role }};
        var userName = '{{ auth()->user()->name }}';
        var userEmail = '';
        var registrantToken = '';
        var zakToken = '';
        var leaveUrl = '{{ url("/user/session") }}';
        var signature = '{{ $jwtToken }}';

        // function getSignature() {
        //     fetch(authEndpoint, {
        //         method: 'POST',
        //         headers: {
        //             'Content-Type': 'application/json'
        //         },
        //         body: JSON.stringify({
        //             meetingNumber: meetingNumber,
        //             role: role
        //         })
        //     }).then((response) => {
        //         return response.json()
        //     }).then((data) => {
        //         console.log(data)
        //         startMeeting(data.signature)
        //     }).catch((error) => {
        //         console.log(error)
        //     })
        // }

        function startMeeting() {

            document.getElementById('zmmtg-root').style.display = 'block'

            ZoomMtg.init({
                leaveUrl: leaveUrl,
                disablePreview: true,
                success: (success) => {
                    console.log(success)
                    console.log(signature);
                    ZoomMtg.join({
                        signature: signature,
                        sdkKey: sdkKey,
                        meetingNumber: meetingNumber,
                        passWord: passWord,
                        userName: userName,
                        userEmail: userEmail,
                        tk: registrantToken,
                        zak: zakToken,
                        success: (success) => {
                            console.log(success)
                        },
                        error: (error) => {
                            console.log(error)
                        },
                    })
                },
                error: (error) => {
                    console.log(error)
                }
            })
        }
    </script>

</body>

</html>